# Generated by Django 3.2.9 on 2021-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='text',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='title',
            field=models.CharField(editable=False, max_length=300),
        ),
    ]
