# Generated by Django 3.2.9 on 2021-11-27 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_auto_20211126_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPage',
            fields=[
                ('id', models.BigIntegerField(
                    auto_created=True,
                    blank=True,
                    db_index=True,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(
                    primary_key=True,
                    serialize=False
                )),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100,
                    null=True
                )),
                ('history_type', models.CharField(
                    choices=[
                        ('+', 'Created'),
                        ('~', 'Changed'),
                        ('-', 'Deleted')
                    ],
                    max_length=1)),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'historical page',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='PageVersion',
        ),
    ]
